name: Moodle Plugin Release

on:
  release:
    types: [ published ]

jobs:
  call-moodle-release-workflow:
    uses: learnweb/moodle-workflows-learnweb/.github/workflows/moodle-release.yml@main
    with:
      plugin-name: 'mod_ratingallocate'
    secrets: inherit
